### ISSUE TITLE
:include-json: and :include-rest-test: break if json field has null value

### ISSUE THREAD

**Issue by jyeakel** [twosigma/znai#305] opened 2019-11-18 20:20 UTC
If JSON has a null value (i.e., {"key": null}) the browser will load a blank screen for the documentation page and the dev console will display:

`TypeError: Cannot convert undefined or null to object`

**Comment by tsiq-karold** [comment] 2019-11-18 21:17
Is this a dupe of https://github.com/twosigma/znai/issues/277?

**Comment by jyeakel** [comment] 2019-11-18 21:30
Looks like it may be. Is the issue only limited to previews? Our internal reporter also noted that non-ASCII characters also create issues: `SyntaxError: Unexpected token ü in JSON at position 256`

**Comment by jyeakel** [comment] 2019-11-18 21:33
Closing as duplicate will add comments to other issue.

**Closed** 2019-11-18 21:32 UTC

**Comment by tsiq-karold** [comment] 2019-11-18 21:45
No, it’s not, I forgot to update the issue but it also impacts build, not just preview.
